apiVersion: apps/v1
kind: Deployment
metadata:
  name: beer-deployment
spec:
  selector:
    matchLabels:
      app: beer
  # tag::replicas[]
  replicas: 3
  # end::replicas[]
  template:
    metadata:
      labels:
        app: beer
    spec:
      containers:
      - name: beer-container
        image: beer-app:1.0-SNAPSHOT
        ports:
        - name: http
          containerPort: 8080
        - name: hazelcast
          containerPort: 5701
---
apiVersion: v1
kind: Service
metadata:
  name: beer-service
spec:
  type: NodePort
  selector:
    app: cart
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31000
